
import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { apiRequest } from "../apiClient";
import { useAuth } from "./AuthContext";
export type BankAccount = {
  id: string;
  name: string;
 type: "bank" | "mobile_money" | "caisse";
  accountNumber: string;
  balance: number;
  openingBalance: number;
  encaissements: number;
  decaissements: number;
  currency: string;
  isDefault: boolean;
  gestionnaire?: string;
  contact?: string;
  email?: string;
};

export type AutoInvoice = {
  id: string;
  blRef: string;
  bdcOrDevisRef: string;
  partyName: string;
  partyType: "supplier" | "client";
  amount: number;
  tvaRate: number;
  totalTTC: number;
  issueDate: string;
  dueDate: string;
  status: "unpaid" | "paid" | "overdue";
  autoGenerated: true;
  items: { productName: string; qty: number; unitPrice: number; total: number }[];
};

export type AppNotification = {
  id: string;
  type: "warning" | "error" | "info" | "success";
  title: string;
  message: string;
  date: string;
  read: boolean;
  module: string;
  documentRef?: string;
  motifRejet?: string;
};

export type AuditEntry = {
  id: string;
  userId: string;
  userName: string;
  userRole: string;
  action: string;
  module: string;
  documentRef: string;
  oldStatus?: string;
  newStatus?: string;
  motifRejet?: string;
  timestamp: string;
  ip?: string;
};

export type Client = {
  id: string;
  raisonSociale: string;
  contact: string;
  adresse: string;
  telephone: string;
  email: string;
  ninea?: string;
  rccm?: string;
  secteur?: string;
  status: "actif" | "inactif";
  solde: number;
  createdAt: string;
  updatedAt: string;
  notes?: string;
};

const INIT_ACCOUNTS: BankAccount[] = [
  {
    id: "acc1",
    name: "BICIS Dakar",
    type: "bank",
    accountNumber: "SN28 0100 1234 5678 9012 3456 789",
    balance: 4850000,
    openingBalance: 4720000,
    encaissements: 480000,
    decaissements: 350000,
    currency: "XOF",
    isDefault: true,
    gestionnaire: "Moussa Diallo",
    contact: "+221 77 123 45 67",
    email: "moussa.diallo@bicis.sn",
  },
  {
    id: "acc2",
    name: "SGBS Dakar",
    type: "bank",
    accountNumber: "SN28 0200 9876 5432 1098 7654 321",
    balance: 2340000,
    openingBalance: 2200000,
    encaissements: 200000,
    decaissements: 60000,
    currency: "XOF",
    isDefault: false,
    gestionnaire: "Fatou Ndiaye",
    contact: "+221 76 234 56 78",
    email: "f.ndiaye@sgbs.sn",
  },
  {
    id: "acc3",
    name: "Caisse Principale",
    type: "caisse",
    accountNumber: "CAISSE-001",
    balance: 350000,
    openingBalance: 400000,
    encaissements: 50000,
    decaissements: 100000,
    currency: "XOF",
    isDefault: false,
    gestionnaire: "Ibrahima Sow",
    contact: "+221 70 345 67 89",
    email: "ibrahima.sow@tresor.sn",
  },
  {
    id: "acc4",
    name: "Caisse Plateau",
    type: "caisse",
    accountNumber: "CAISSE-002",
    balance: 120000,
    openingBalance: 150000,
    encaissements: 20000,
    decaissements: 50000,
    currency: "XOF",
    isDefault: false,
    gestionnaire: "Aminata Mbaye",
    contact: "+221 78 456 78 90",
    email: "a.mbaye@tresor.sn",
  },
];

const INIT_AUTO_INVOICES: AutoInvoice[] = [
  {
    id: "inv1",
    blRef: "BL-F-2024-002",
    bdcOrDevisRef: "BDC-2024-008",
    partyName: "Fournisseur Alpha SARL",
    partyType: "supplier",
    amount: 120000,
    tvaRate: 18,
    totalTTC: 141600,
    issueDate: "2024-11-15",
    dueDate: "2024-12-15",
    status: "paid",
    autoGenerated: true,
    items: [
      { productName: "Fournitures de bureau", qty: 10, unitPrice: 12000, total: 120000 },
    ],
  },
  {
    id: "inv2",
    blRef: "BL-C-2024-002",
    bdcOrDevisRef: "DEVIS-2024-012",
    partyName: "Client Beta SA",
    partyType: "client",
    amount: 450000,
    tvaRate: 18,
    totalTTC: 531000,
    issueDate: "2024-11-20",
    dueDate: "2024-12-20",
    status: "unpaid",
    autoGenerated: true,
    items: [
      { productName: "Prestation de service", qty: 1, unitPrice: 450000, total: 450000 },
    ],
  },
];

const INIT_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif1",
    type: "warning",
    title: "Paiement en retard",
    message: "La facture FAC-2024-031 de Fournisseur Alpha est en retard de 5 jours.",
    date: "2024-12-01T09:00:00Z",
    read: false,
    module: "invoices",
  },
  {
    id: "notif2",
    type: "warning",
    title: "Échéance dépassée",
    message: "La facture client FAC-C-2024-015 est échue depuis 3 jours. Relance nécessaire.",
    date: "2024-12-02T10:30:00Z",
    read: false,
    module: "invoices",
  },
  {
    id: "notif3",
    type: "info",
    title: "Nouveau bon de commande",
    message: "Un nouveau BDC-2024-022 a été créé et attend validation.",
    date: "2024-12-03T08:15:00Z",
    read: false,
    module: "purchases",
  },
  {
    id: "notif4",
    type: "success",
    title: "Paiement effectué",
    message: "Le virement de 141 600 XOF vers Fournisseur Alpha a été confirmé.",
    date: "2024-11-28T14:00:00Z",
    read: true,
    module: "payments",
  },
  {
    id: "notif5",
    type: "warning",
    title: "Solde caisse faible",
    message: "Le solde de la Caisse Plateau est inférieur au seuil minimum (120 000 XOF).",
    date: "2024-11-30T16:45:00Z",
    read: true,
    module: "treasury",
  },
];

const INIT_CLIENTS: Client[] = [
  {
    id: "cli1",
    raisonSociale: "SONATEL SA",
    contact: "Aliou DIALLO",
    adresse: "Immeuble Sonatel, Route de Ouakam, Dakar",
    telephone: "+221 33 839 00 00",
    email: "procurement@sonatel.sn",
    ninea: "SN-001234567",
    rccm: "SN-DKR-2005-B-12345",
    secteur: "Télécommunications",
    status: "actif",
    solde: 2450000,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-11-20T14:30:00Z",
    notes: "Client prioritaire — règlement à 30 jours",
  },
  {
    id: "cli2",
    raisonSociale: "TotalEnergies Sénégal",
    contact: "Marie FAYE",
    adresse: "Rue Huart, Plateau, Dakar",
    telephone: "+221 33 839 30 00",
    email: "achats@totalenergies.sn",
    ninea: "SN-002345678",
    rccm: "SN-DKR-2001-B-8765",
    secteur: "Énergie",
    status: "actif",
    solde: 0,
    createdAt: "2024-02-10T09:00:00Z",
    updatedAt: "2024-10-05T11:00:00Z",
  },
  {
    id: "cli3",
    raisonSociale: "Groupe PATISEN",
    contact: "Cheikh NDIAYE",
    adresse: "Zone Industrielle de Mbao, Dakar",
    telephone: "+221 33 879 00 10",
    email: "finance@patisen.sn",
    ninea: "SN-003456789",
    secteur: "Agroalimentaire",
    status: "actif",
    solde: 780000,
    createdAt: "2024-03-05T08:00:00Z",
    updatedAt: "2024-09-18T16:00:00Z",
  },
  {
    id: "cli4",
    raisonSociale: "Hôpital Principal de Dakar",
    contact: "Dr. Fatou MBODJ",
    adresse: "Avenue Nelson Mandela, Dakar",
    telephone: "+221 33 839 50 00",
    email: "direction@hpd.sn",
    ninea: "SN-004567890",
    secteur: "Santé",
    status: "actif",
    solde: 1200000,
    createdAt: "2024-04-20T10:30:00Z",
    updatedAt: "2024-11-01T09:00:00Z",
  },
  {
    id: "cli5",
    raisonSociale: "Université Cheikh Anta Diop",
    contact: "Prof. Moussa SOW",
    adresse: "Campus UCAD, Dakar-Fann",
    telephone: "+221 33 825 00 64",
    email: "daf@ucad.edu.sn",
    ninea: "SN-005678901",
    secteur: "Enseignement supérieur",
    status: "inactif",
    solde: 0,
    createdAt: "2024-05-12T14:00:00Z",
    updatedAt: "2024-08-30T10:00:00Z",
    notes: "Contrat suspendu — à réactiver en janvier 2025",
  },
];

type AppDataContextType = {
  bankAccounts: BankAccount[];
  selectedAccount: BankAccount | null;
  setSelectedAccount: (account: BankAccount) => void;
 addBankAccount: (account: {
  name: string;
  account_type: "BANK" | "MOBILE_MONEY" | "CASH";
  account_number: string;
  bank_name: string;
  currency: string;
  opening_balance: number;
  is_active: boolean;
  manager_name: string;
  manager_phone: string;
  manager_email: string;
}) => Promise<BankAccount>;
updateBankAccount: (
  id: string,
  updates: Partial<BankAccount> & {
    account_type?: "BANK" | "MOBILE_MONEY" | "CASH";
    account_number?: string;
    opening_balance?: number;
    bank_name?: string;
    manager_name?: string;
    manager_phone?: string;
    manager_email?: string;
    is_active?: boolean;
  }
) => Promise<BankAccount>;
  deleteBankAccount: (id: string) => void;
  autoInvoices: AutoInvoice[];
  addAutoInvoice: (invoice: Omit<AutoInvoice, "id">) => void;
  updateInvoiceStatus: (id: string, status: AutoInvoice["status"]) => void;
  notifications: AppNotification[];
  unreadCount: number;
  markNotificationRead: (id: string) => void;
  markAllRead: () => void;
  addNotification: (notif: Omit<AppNotification, "id" | "date" | "read">) => void;
  auditLog: AuditEntry[];
  addAuditEntry: (entry: Omit<AuditEntry, "id" | "timestamp">) => void;
  clients: Client[];
  addClient: (client: Omit<Client, "id" | "createdAt" | "updatedAt">) => Client;
  updateClient: (id: string, updates: Partial<Omit<Client, "id" | "createdAt">>) => void;
  toggleClientStatus: (id: string) => void;
  deleteClient: (id: string) => void;
};

const AppDataContext = createContext<AppDataContextType | null>(null);

export function AppDataProvider({ children }: { children: ReactNode }) {
    const { user, isInitialized } = useAuth();
  const [bankAccounts, setBankAccounts] = useState<BankAccount[]>([]);

  const [selectedAccount, setSelectedAccount] =
  useState<BankAccount | null>(null);
  const [autoInvoices, setAutoInvoices] = useState<AutoInvoice[]>(INIT_AUTO_INVOICES);
 const [notifications, setNotifications] = useState<AppNotification[]>([]);
useEffect(() => {
  if (!isInitialized || !user) {
    return;
  }

  const loadNotifications = async () => {
    try {
      const response = await apiRequest(
        "/v1/notifications/"
      );

      console.log(
        "=== NOTIFICATIONS DJANGO ===",
        response
      );

      const data = response.results ?? response ?? [];

      setNotifications(
        data.map((n: any) => ({
          id: n.id,
          type: n.type || "info",
          title: n.title || "Notification",
          message: n.message || "",
          read: n.is_read ?? n.read ?? false,
          date: n.created_at || n.date,
          module: n.module || "",
          documentRef: n.document_ref,
          motifRejet: n.motif_rejet,
        }))
      );
    } catch (error) {
      console.error(
        "=== ERREUR NOTIFICATIONS DJANGO ===",
        error
      );
    }
  };

  loadNotifications();
}, [isInitialized, user]);

useEffect(() => {
  if (!isInitialized || !user) {
    return;
  }

  const loadUnreadCount = async () => {
    try {
      const response = await apiRequest(
        "/v1/notifications/unread-count/"
      );

      console.log(
        "=== UNREAD COUNT DJANGO ===",
        response
      );
    } catch (error) {
      console.error(
        "=== ERREUR UNREAD COUNT DJANGO ===",
        error
      );
    }
  };

  loadUnreadCount();
}, [isInitialized, user]);
  const [auditLog, setAuditLog] = useState<AuditEntry[]>([]);
  const [clients, setClients] = useState<Client[]>(INIT_CLIENTS);

 const addBankAccount = async (
  account: {
    name: string;
    account_type: "BANK" | "MOBILE_MONEY" | "CASH";
    account_number: string;
    bank_name: string;
    currency: string;
    opening_balance: number;
    is_active: boolean;
    manager_name: string;
    manager_phone: string;
    manager_email: string;
  }
): Promise<BankAccount> => {
  try {
    console.log("=== AJOUT COMPTE DJANGO ===", account);

    const response = await apiRequest("/v1/treasury/accounts/", {
      method: "POST",
      body: JSON.stringify({
  name: account.name,
  account_type: account.account_type,
  account_number: account.account_number || "",
  bank_name: account.bank_name || "",
  currency: "XOF",
  opening_balance: String(account.opening_balance || 0),
  is_active: account.is_active,
  manager_name: account.manager_name || "",
  manager_phone: account.manager_phone || "",
  manager_email: account.manager_email || "",
}),
    });

    console.log("=== COMPTE DJANGO CRÉÉ ===", response);

    const newAccount: BankAccount = {
      id: response.id,
      name: response.name,
      type: response.account_type === "BANK" ? "bank" : "caisse",
      accountNumber: response.account_number || "",
      balance: Number(response.current_balance || 0),
      openingBalance: Number(response.opening_balance || 0),
      encaissements: 0,
      decaissements: 0,
      currency: response.currency || "XOF",
      isDefault: false,
    };

    setBankAccounts((prev) => [...prev, newAccount]);

    return newAccount;
  } catch (error) {
    console.error("=== ERREUR AJOUT COMPTE DJANGO ===", error);
    throw error;
  }
};

  const updateBankAccount = async (
  id: string,
  updates: Partial<BankAccount> & {
  account_type?: "BANK" | "MOBILE_MONEY" | "CASH";
  account_number?: string;
  opening_balance?: number;
  bank_name?: string;
  manager_name?: string;
  manager_phone?: string;
  manager_email?: string;
  is_active?: boolean;
}
): Promise<BankAccount> => {
  try {
    console.log(
  "=== UPDATE ACCOUNT REÇU ===",
  JSON.stringify(updates, null, 2)
);
    console.log("=== MODIFICATION COMPTE DJANGO ===", id, updates);

    const response = await apiRequest(
      `/v1/treasury/accounts/${id}/`,
      {
        method: "PUT",
        body: JSON.stringify({
  name: updates.name,
  account_type:
    updates.account_type ??
    (updates.type === "bank"
      ? "BANK"
      : updates.type === "caisse"
        ? "CASH"
        : "MOBILE_MONEY"),
  account_number:
    updates.account_number ??
    updates.accountNumber ??
    "",
  bank_name: updates.bank_name ?? "",
  currency: "XOF",
  opening_balance:
    updates.opening_balance ??
    updates.openingBalance ??
    0,
  is_active: updates.is_active ?? true,
  manager_name: updates.manager_name ?? "",
  manager_phone: updates.manager_phone ?? "",
  manager_email: updates.manager_email ?? "",
}),
      }
    );

    console.log(
      "=== COMPTE DJANGO MODIFIÉ ===",
      response
    );

    const updatedAccount: BankAccount = {
      id: response.id,
      name: response.name,
      type:
        response.account_type === "BANK"
          ? "bank"
          : "caisse",
      accountNumber: response.account_number || "",
      balance: Number(response.current_balance || 0),
      openingBalance: Number(
        response.opening_balance || 0
      ),
      encaissements:
        updates.encaissements ?? 0,
      decaissements:
        updates.decaissements ?? 0,
      currency: response.currency || "XOF",
      isDefault: updates.isDefault ?? false,
      gestionnaire:
        updates.gestionnaire || "",
      contact:
        updates.contact || "",
      email:
        updates.email || "",
    };

    setBankAccounts((prev) =>
      prev.map((account) =>
        account.id === id
          ? updatedAccount
          : account
      )
    );

    if (selectedAccount?.id === id) {
      setSelectedAccount(updatedAccount);
    }

    return updatedAccount;
  } catch (error) {
    console.error(
      "=== ERREUR MODIFICATION COMPTE DJANGO ===",
      error
    );
    throw error;
  }
};
  const deleteBankAccount = (id: string) => {
    setBankAccounts((prev) => prev.filter((a) => a.id !== id));
    if (selectedAccount?.id === id) {
      const remaining = bankAccounts.filter((a) => a.id !== id);
      setSelectedAccount(remaining.find((a) => a.isDefault) ?? remaining[0] ?? null);
    }
  };

  const addAutoInvoice = (invoice: Omit<AutoInvoice, "id">) => {
    const newInvoice: AutoInvoice = { ...invoice, id: crypto.randomUUID() };
    setAutoInvoices((prev) => [...prev, newInvoice]);
  };

  const updateInvoiceStatus = (id: string, status: AutoInvoice["status"]) => {
    setAutoInvoices((prev) =>
      prev.map((inv) => (inv.id === id ? { ...inv, status } : inv))
    );
  };

 const [unreadCount, setUnreadCount] = useState(0);

  const markNotificationRead = async (id: string) => {
  try {
    await apiRequest(`/v1/notifications/${id}/mark-read/`, {
      method: "POST",
    });

    setNotifications((prev) =>
      prev.map((n) =>
        n.id === id ? { ...n, read: true } : n
      )
    );

    console.log(
      "=== NOTIFICATION MARQUÉE LUE ===",
      id
    );
  } catch (error) {
    console.error(
      "=== ERREUR MARK NOTIFICATION ===",
      error
    );
  }
};

 const markAllRead = async () => {
  try {
    await apiRequest("/v1/notifications/mark-all-read/", {
      method: "POST",
    });

    setNotifications((prev) =>
      prev.map((n) => ({ ...n, read: true }))
    );

    console.log("=== TOUTES LES NOTIFICATIONS MARQUÉES LUES ===");
  } catch (error) {
    console.error(
      "=== ERREUR MARK ALL NOTIFICATIONS ===",
      error
    );
  }
};

  const addAuditEntry = (entry: Omit<AuditEntry, "id" | "timestamp">) => {
    setAuditLog(prev => [{
      ...entry,
      id: crypto.randomUUID(),
      timestamp: new Date().toISOString(),
    }, ...prev]);
  };

  const addNotification = (notif: Omit<AppNotification, "id" | "date" | "read">) => {
    const newNotif: AppNotification = {
      ...notif,
      id: crypto.randomUUID(),
      date: new Date().toISOString(),
      read: false,
    };
    setNotifications((prev) => [newNotif, ...prev]);
  };

  const addClient = (client: Omit<Client, "id" | "createdAt" | "updatedAt">): Client => {
    const newClient: Client = {
      ...client,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    setClients(prev => [newClient, ...prev]);
    return newClient;
  };

  const updateClient = (id: string, updates: Partial<Omit<Client, "id" | "createdAt">>) => {
    setClients(prev => prev.map(c => c.id === id
      ? { ...c, ...updates, updatedAt: new Date().toISOString() }
      : c
    ));
  };

  const toggleClientStatus = (id: string) => {
    setClients(prev => prev.map(c => c.id === id
      ? { ...c, status: c.status === "actif" ? "inactif" : "actif", updatedAt: new Date().toISOString() }
      : c
    ));
  };

  const deleteClient = (id: string) => {
    setClients(prev => prev.filter(c => c.id !== id));
  };

  return (
    <AppDataContext.Provider
      value={{
        bankAccounts,
        selectedAccount,
        setSelectedAccount,
        addBankAccount,
        updateBankAccount,
        deleteBankAccount,
        autoInvoices,
        addAutoInvoice,
        updateInvoiceStatus,
        notifications,
        unreadCount,
        markNotificationRead,
        markAllRead,
        addNotification,
        auditLog,
        addAuditEntry,
        clients,
        addClient,
        updateClient,
        toggleClientStatus,
        deleteClient,
      }}
    >
      {children}
    </AppDataContext.Provider>
  );
}

export function useAppData() {
  const ctx = useContext(AppDataContext);
  if (!ctx) throw new Error("useAppData must be used within AppDataProvider");
  return ctx;
}
