import { useEffect, useState } from "react";
import { Search, Plus, Eye, Send, Trash2, X, CheckCircle, XCircle, Edit, FileText, CreditCard } from "lucide-react";
import { useLanguage } from "../../context/LanguageContext";
import { useAppData } from "../../context/AppDataContext";
import { useAuth } from "../../context/AuthContext";
import { apiRequest } from "../../apiClient";
import {
  getCustomerInvoices,
  createCustomerInvoice,
  updateCustomerInvoice,
  sendCustomerInvoiceToCustomer,
  validateCustomerInvoiceByCustomer,
  deleteCustomerInvoice,
} from "../../data/customerInvoicesApi";
import { getCustomerDeliveries } from "../../data/customerDeliveriesData";
// ---------- types ----------
type Invoice = {
  id: string;
  client: string;
  bdcRef: string;
  blRef: string;
  amount: number;
  status: string;
  issueDate: string;
  dueDate: string;
  tvaRate: number;
  isPaid: boolean;
  autoGenerated: boolean;
  items: { designation: string; quantity: number; unitPrice: number; total: number }[];
  paidAt?: string;
  paymentMethod?: string;
  deletedAt?: string;
};

type InvoiceItem = {
  id: number;
  designation: string;
  quantity: number;
  unitPrice: number;
};

// ---------- static data ----------
const CLIENT_DATA = [
  {
    ref: "CLI-001", name: "Client ABC", bdcRef: "BC-2024-088", blRef: "BL-C-2024-001",
    blDate: "2026-04-19",
    items: [
      { designation: "Prestation conseil", qty: 10, unitPrice: 150000, total: 1500000 },
      { designation: "Formation équipe", qty: 2, unitPrice: 450000, total: 900000 },
    ],
    tvaRate: 18,
  },
  {
    ref: "CLI-002", name: "Société Delta", bdcRef: "BC-2024-087", blRef: "BL-C-2024-002",
    blDate: "2026-04-15",
    items: [
      { designation: "Fournitures de bureau", qty: 50, unitPrice: 25000, total: 1250000 },
    ],
    tvaRate: 18,
  },
  {
    ref: "CLI-003", name: "Entreprise Gamma", bdcRef: "BC-2024-086", blRef: "BL-C-2024-003",
    blDate: "2026-04-10",
    items: [
      { designation: "Matériel informatique", qty: 8, unitPrice: 720000, total: 5760000 },
      { designation: "Licences logiciels", qty: 8, unitPrice: 85000, total: 680000 },
    ],
    tvaRate: 18,
  },
];

const PAYMENT_METHODS = ["Virement bancaire", "Chèque", "Espèces", "Carte bancaire"];

const initialInvoices: Invoice[] = [
  {
    id: "FACT-CLI-2024-125",
    client: "Client ABC Corp",
    bdcRef: "DEV-2024-045",
    blRef: "BL-CLI-2024-020",
    amount: 65000,
    status: "paid",
    issueDate: "2026-04-01",
    dueDate: "2026-04-30",
    tvaRate: 18,
    isPaid: true,
    autoGenerated: false,
    items: [
      { designation: "Conseil en stratégie", quantity: 2, unitPrice: 20000, total: 40000 },
      { designation: "Formation équipe", quantity: 5, unitPrice: 5000, total: 25000 },
    ],
  },
  {
    id: "FACT-CLI-2024-124",
    client: "Entreprise XYZ Ltd",
    bdcRef: "DEV-2024-044",
    blRef: "BL-CLI-2024-019",
    amount: 42000,
    status: "unpaid",
    issueDate: "2026-04-05",
    dueDate: "2026-04-28",
    tvaRate: 18,
    isPaid: false,
    autoGenerated: false,
    items: [
      { designation: "Développement logiciel", quantity: 3, unitPrice: 14000, total: 42000 },
    ],
  },
  {
    id: "FACT-CLI-2024-123",
    client: "Société DEF SARL",
    bdcRef: "DEV-2024-043",
    blRef: "BL-CLI-2024-018",
    amount: 18500,
    status: "unpaid",
    issueDate: "2026-03-20",
    dueDate: "2026-04-20",
    tvaRate: 18,
    isPaid: false,
    autoGenerated: false,
    items: [
      { designation: "Maintenance applicative", quantity: 1, unitPrice: 18500, total: 18500 },
    ],
  },
];

const statusConfig = {
  paid: { label: "Payée", color: "bg-green-100 text-green-700" },
  partial: { label: "Partielle", color: "bg-yellow-100 text-yellow-700" },
  unpaid: { label: "Impayée", color: "bg-red-100 text-red-700" },
  sent: { label: "Envoyée", color: "bg-blue-100 text-blue-700" },
  draft: { label: "Brouillon", color: "bg-gray-100 text-gray-700" },
  overdue: { label: "En retard", color: "bg-red-100 text-red-700" },
};

const getDueDateStatus = (dueDate: string, isPaid: boolean) => {
  if (isPaid) {
    return {
      color: "bg-green-500",
      label: "Payée",
      textColor: "text-green-700",
    };
  }

  const due = new Date(dueDate);
  const today = new Date();

  // Comparaison uniquement sur la date, sans l'heure
  due.setHours(0, 0, 0, 0);
  today.setHours(0, 0, 0, 0);

  if (due < today) {
    return {
      color: "bg-red-500",
      label: "Dépassée",
      textColor: "text-red-700",
    };
  }

  return {
    color: "bg-green-500",
    label: "À venir",
    textColor: "text-green-700",
  };
};
export function ClientInvoices() {
  useEffect(() => {
  const loadCustomerInvoices = async () => {
    try {
      console.log("=== FACTURES CLIENTS DJANGO ===");

      const response = await getCustomerInvoices();
setDjangoInvoices(response.results ?? []);
      console.log(
  "Réponse Django factures clients :",
  JSON.stringify(response, null, 2)
);

    } catch (error) {
      console.error("Erreur GET factures clients Django :", error);
    }
  };

  loadCustomerInvoices();
}, []);

useEffect(() => {
  const loadCustomerDeliveries = async () => {
    try {
      console.log("=== BL CLIENTS DJANGO POUR FACTURES ===");

      const response = await getCustomerDeliveries();

      console.log(
        "Réponse Django BL clients :",
        JSON.stringify(response, null, 2)
      );

      setCustomerDeliveries(response.results ?? []);
    } catch (error) {
      console.error("Erreur GET BL clients Django :", error);
    }
  };

  loadCustomerDeliveries();
}, []);
  const { lang, t } = useLanguage();
  const { autoInvoices, updateInvoiceStatus } = useAppData();
  const { hasPermission, hasRole } = useAuth();

  // RBAC

const canCreate   = hasPermission("client_invoices:create");
const canEdit     = hasPermission("client_invoices:edit");
const canValidate = hasPermission("client_invoices:validate");
const canReject   = hasPermission("client_invoices:reject");
const canSend     = hasPermission("client_invoices:send");
const canDelete   = hasPermission("client_invoices:delete");
const canMarkPaid = hasPermission("client_invoices:manage");

const isViewOnly =
  !canCreate &&
  !canEdit &&
  !canValidate &&
  !canReject &&
  !canSend &&
  !canDelete &&
  !canMarkPaid;

  const [invoices, setInvoices] = useState<Invoice[]>(initialInvoices);
  const [djangoInvoices, setDjangoInvoices] = useState<any[]>([]);
  const [customerDeliveries, setCustomerDeliveries] = useState<any[]>([]);

  const mappedDjangoInvoices: Invoice[] = djangoInvoices.map((invoice) => ({
  id: invoice.reference,
  client: invoice.customer_detail?.raison_sociale ?? "-",
  bdcRef: invoice.order_reference ?? "-",
  blRef: invoice.delivery_reference ?? "-",
  amount: Number(invoice.total_amount_ttc ?? 0),
  status: invoice.status,
  issueDate: invoice.invoice_date,
  dueDate: invoice.due_date,
  tvaRate: Number(invoice.total_tax ?? 0),
  isPaid: invoice.payment_status === "PAID",
  autoGenerated: true,
  items: (invoice.lines ?? []).map((line: any) => ({
    designation: line.product_detail?.name ?? "-",
    quantity: Number(line.quantity ?? 0),
    unitPrice: Number(line.unit_price ?? 0),
    total: Number(line.total_incl_tax ?? 0),
  })),
}));
  const [searchTerm, setSearchTerm] = useState("");
  const [showModal, setShowModal] = useState(false);
  const [editingInvoiceId, setEditingInvoiceId] = useState<string | null>(null);
  const [showDetailModal, setShowDetailModal] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);

  // Payment modal state
  const [payModal, setPayModal] = useState<{ invoiceId: string; method: string } | null>(null);

  // Track which auto-invoice IDs have been deleted locally
  const [deletedAutoIds, setDeletedAutoIds] = useState<Set<string>>(new Set());
  // Track extra fields (status, isPaid, paidAt, paymentMethod) for auto-invoices
  const [autoClientOverrides, setAutoClientOverrides] = useState<Record<string, Partial<Invoice>>>({});

  const today = new Date().toISOString().split("T")[0];

  // Form state
  const [selectedClientRef, setSelectedClientRef] = useState<string>("");
  const [formLocked, setFormLocked] = useState(false);
  const [formData, setFormData] = useState({
    client: "",
    bdcRef: "",
    blRef: "",
     deliveryId: "",
    issueDate: today,
    dueDate: "",
    tvaRate: 18,
  });

  const [formItems, setFormItems] = useState<InvoiceItem[]>([
    { id: 1, designation: "", quantity: 1, unitPrice: 0 },
  ]);

  // Merge auto-generated client invoices
  const autoClientInvoices = autoInvoices
    .filter(i => i.partyType === "client" && !deletedAutoIds.has(i.id))
    .map(i => {
      const override = autoClientOverrides[i.id] ?? {};
      return {
        id: i.id,
        client: i.partyName,
        bdcRef: i.bdcOrDevisRef,
        blRef: i.blRef,
        amount: i.totalTTC,
        status: override.status ?? (i.status === "paid" ? "paid" : "unpaid"),
        issueDate: i.issueDate,
        dueDate: i.dueDate,
        tvaRate: i.tvaRate,
        isPaid: override.isPaid ?? (i.status === "paid"),
        autoGenerated: true,
        items: i.items.map(x => ({ designation: x.productName, quantity: x.qty, unitPrice: x.unitPrice, total: x.total })),
        paidAt: override.paidAt,
        paymentMethod: override.paymentMethod,
      } as Invoice;
    });

  const allInvoices = [...invoices, ...autoClientInvoices];

  const filteredInvoices = mappedDjangoInvoices.filter(
  (invoice) =>
    invoice.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
    invoice.client.toLowerCase().includes(searchTerm.toLowerCase())
);
  const blHasAutoInvoice = (blRef: string) =>
    blRef.trim() !== "" && autoClientInvoices.some(inv => inv.blRef === blRef.trim());

  // Form calculations
  const calcSubtotal = () => formItems.reduce((s, i) => s + i.quantity * i.unitPrice, 0);
  const calcTVA = () => calcSubtotal() * (formData.tvaRate / 100);
  const calcTotal = () => calcSubtotal() + calcTVA();

  const handleAddFormItem = () => {
    setFormItems([...formItems, { id: Date.now(), designation: "", quantity: 1, unitPrice: 0 }]);
  };

  const handleRemoveFormItem = (id: number) => {
    if (formItems.length > 1) setFormItems(formItems.filter(i => i.id !== id));
  };

  const handleFormItemChange = (id: number, field: string, value: any) => {
    setFormItems(formItems.map(i => i.id === id ? { ...i, [field]: value } : i));
  };

  // Client auto-fill
  const handleClientSelect = (deliveryId: string) => {
  setSelectedClientRef(deliveryId);

  if (!deliveryId) {
    setFormLocked(false);
    return;
  }

  const delivery = customerDeliveries.find(
    (item: any) => item.id === deliveryId
  );

  if (!delivery) return;

  setFormData(prev => ({
    ...prev,
    client: delivery.customer_detail?.raison_sociale ?? "",
    bdcRef: delivery.order_reference ?? "",
    blRef: delivery.reference ?? "",
    deliveryId: delivery.id,
  }));

  setFormItems(
    (delivery.items ?? []).map((item: any, idx: number) => ({
      id: idx + 1,
      designation: item.product_detail?.name ?? "",
      quantity: Number(
        item.quantity_delivered ?? item.quantity_ordered ?? item.quantity ?? 0
      ),
      unitPrice: Number(
        item.product_detail?.unit_price ?? item.unit_price ?? 0
      ),
    }))
  );

  setFormLocked(true);
};
  const handleSubmit = async (e: React.FormEvent) => {
  e.preventDefault();

  if (!editingInvoiceId && !formData.deliveryId) {
  console.error("Aucun BL client sélectionné");
  return;
}

  try {
  if (editingInvoiceId) {
    console.log("=== MODIFICATION FACTURE CLIENT DJANGO ===");
  } else {
    console.log("=== CRÉATION FACTURE CLIENT DJANGO ===");
  }

    const payload = {
      delivery: formData.deliveryId,
      invoice_date: formData.issueDate,
      due_date: formData.dueDate,
      notes: "Facture créée depuis DIPERFLO",
    };

    if (editingInvoiceId) {
  const payload = {
    invoice_date: formData.issueDate,
    due_date: formData.dueDate,
    notes: "Facture modifiée depuis DIPERFLO",
  };

  console.log(
    "Payload modification facture client :",
    JSON.stringify(payload, null, 2)
  );

  const response = await updateCustomerInvoice(
    editingInvoiceId,
    payload
  );

  console.log(
    "Facture client modifiée dans Django :",
    JSON.stringify(response, null, 2)
  );

  setDjangoInvoices((prev) =>
    prev.map((inv) =>
      inv.id === editingInvoiceId ? { ...inv, ...response } : inv
    )
  );

  setShowModal(false);
  setEditingInvoiceId(null);
  resetForm();

  console.log("=== FACTURE CLIENT MODIFIÉE AVEC SUCCÈS ===");

  return;
}

    console.log(
      "Payload facture client :",
      JSON.stringify(payload, null, 2)
    );

    const response = await createCustomerInvoice(payload);

    console.log(
      "Facture client créée dans Django :",
      JSON.stringify(response, null, 2)
    );

    setDjangoInvoices((prev) => [response, ...prev]);

    setShowModal(false);
    resetForm();

    console.log("=== FACTURE CLIENT CRÉÉE AVEC SUCCÈS ===");
  } catch (error) {
    console.error(
      "Erreur création facture client Django :",
      error
    );
  }
};

  const resetForm = () => {
    setSelectedClientRef("");
    setFormLocked(false);
    setFormData({ client: "", bdcRef: "", blRef: "",  deliveryId: "", issueDate: today, dueDate: "", tvaRate: 18 });
    setFormItems([{ id: 1, designation: "", quantity: 1, unitPrice: 0 }]);
  };

  const handleViewDetails = (invoice: any) => {
    setSelectedInvoice(invoice);
    setShowDetailModal(true);
  };

 const handleSendInvoice = async (invoiceId: string) => {
  if (!confirm("Envoyer cette facture au client ?")) {
    return;
  }

  try {
    console.log("=== ENVOI FACTURE CLIENT DJANGO ===");
    console.log("Facture :", invoiceId);

    const invoice = djangoInvoices.find(
      (inv: any) => inv.reference === invoiceId
    );

    if (!invoice) {
      console.error("Facture Django introuvable :", invoiceId);
      return;
    }

    const response = await sendCustomerInvoiceToCustomer(invoice.id);

    console.log(
      "Facture envoyée au client :",
      JSON.stringify(response, null, 2)
    );

    setDjangoInvoices((prev) =>
      prev.map((inv) =>
        inv.id === invoice.id ? response : inv
      )
    );

    if (showDetailModal && selectedInvoice?.id === invoiceId) {
      setSelectedInvoice({
        ...selectedInvoice,
        status: response.status,
      });
    }

    console.log("=== FACTURE ENVOYÉE AVEC SUCCÈS ===");
  } catch (error) {
    console.error(
      "Erreur envoi facture client Django :",
      error
    );
  }
};

const handleValidateInvoice = async (invoiceId: string) => {
  if (!confirm("Valider cette facture en tant que client ?")) {
    return;
  }

  try {
    console.log("=== VALIDATION FACTURE CLIENT DJANGO ===");
    console.log("Facture :", invoiceId);

    const invoice = djangoInvoices.find(
      (inv: any) => inv.reference === invoiceId
    );

    if (!invoice) {
      console.error("Facture Django introuvable :", invoiceId);
      return;
    }

    const response = await validateCustomerInvoiceByCustomer(invoice.id);

    console.log(
      "Facture validée par le client :",
      JSON.stringify(response, null, 2)
    );

    setDjangoInvoices((prev) =>
      prev.map((inv) =>
        inv.id === invoice.id ? response : inv
      )
    );

    if (showDetailModal && selectedInvoice?.id === invoiceId) {
      setSelectedInvoice({
        ...selectedInvoice,
        status: response.status,
      });
    }

    console.log("=== FACTURE VALIDÉE PAR LE CLIENT ===");
  } catch (error) {
    console.error(
      "Erreur validation facture client Django :",
      error
    );
  }
};
const handleRejectInvoice = async (invoiceId: string) => {
  const reason = prompt("Veuillez saisir le motif du rejet :");

  if (!reason || !reason.trim()) {
    return;
  }

  try {
    console.log("=== REJET FACTURE CLIENT DJANGO ===");
    console.log("Facture :", invoiceId);
    console.log("Motif :", reason);

    const invoice = djangoInvoices.find(
      (inv: any) => inv.reference === invoiceId
    );

    if (!invoice) {
      console.error("Facture Django introuvable :", invoiceId);
      return;
    }

    console.log("=== UTILISATEUR REJET FACTURE ===");
console.log("User :", localStorage.getItem("auth_user"));
console.log("Token présent :", !!localStorage.getItem("access_token"));
    const response = await apiRequest(
      
      `/v1/invoices/customer/${invoice.id}/reject/`,
      {
        method: "POST",
        body: JSON.stringify({
          reason: reason.trim(),
        }),
      }
    );

    console.log(
      "Facture rejetée par le client :",
      JSON.stringify(response, null, 2)
    );

    setDjangoInvoices((prev) =>
      prev.map((inv) =>
        inv.id === invoice.id ? response : inv
      )
    );

    if (showDetailModal && selectedInvoice?.id === invoiceId) {
      setSelectedInvoice({
        ...selectedInvoice,
        status: response.status,
      });
    }

    console.log("=== FACTURE REJETÉE PAR LE CLIENT ===");
  } catch (error) {
    console.error(
      "Erreur rejet facture client Django :",
      error
    );
  }
};

  // ---------- action handlers ----------
  const handleMarkPaid = (invoiceId: string, method: string) => {
    const isAuto = autoInvoices.some(i => i.id === invoiceId);
    if (isAuto) {
      updateInvoiceStatus(invoiceId, "paid");
      setAutoClientOverrides(prev => ({
        ...prev,
        [invoiceId]: { ...prev[invoiceId], status: "paid", isPaid: true, paidAt: new Date().toISOString(), paymentMethod: method },
      }));
    } else {
      setInvoices(prev => prev.map(inv => inv.id === invoiceId
        ? { ...inv, status: "paid", isPaid: true, paidAt: new Date().toISOString(), paymentMethod: method }
        : inv
      ));
    }
    setPayModal(null);
    setSelectedInvoice(null);
    setShowDetailModal(false);
  };

  const handleDelete = async (invoiceId: string) => {
  if (!window.confirm("Supprimer cette facture définitivement ?")) {
    return;
  }

  try {
    console.log("=== SUPPRESSION FACTURE CLIENT DJANGO ===");
    console.log("Facture :", invoiceId);

    const invoice = djangoInvoices.find(
      (inv: any) => inv.reference === invoiceId
    );

    if (!invoice) {
      console.error("Facture Django introuvable :", invoiceId);
      return;
    }

    console.log("UUID Django :", invoice.id);

    await deleteCustomerInvoice(invoice.id);

    console.log("Facture supprimée de Django :", invoice.id);

    setDjangoInvoices((prev) =>
      prev.filter((inv: any) => inv.id !== invoice.id)
    );

    setSelectedInvoice(null);
    setShowDetailModal(false);

    console.log("=== FACTURE CLIENT SUPPRIMÉE AVEC SUCCÈS ===");
  } catch (error) {
    console.error(
      "Erreur suppression facture client Django :",
      error
    );
  }
};

  const blWarning = blHasAutoInvoice(formData.blRef);

  const availableCustomerDeliveries = customerDeliveries.filter(
  (delivery: any) => {
    if (delivery.status !== "VALIDATED") {
      return false;
    }

    const alreadyInvoiced = djangoInvoices.some(
      (invoice: any) => invoice.delivery === delivery.id
    );

    return !alreadyInvoiced;
  }
);

return (
  <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
        <div>
          <h1 className="text-2xl text-gray-900">{t.clientInvoices.title[lang]}</h1>
          <p className="text-gray-600 mt-1">{t.clientInvoices.subtitle[lang]}</p>
        </div>
        <div className="flex gap-3">
          {canCreate && (
            <button
              onClick={() => setShowModal(true)}
              className="flex items-center justify-center px-4 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-lg hover:from-blue-700 hover:to-indigo-700 transition"
            >
              <Plus className="w-5 h-5 mr-2" />
              Nouvelle facture
            </button>
          )}
        </div>
      </div>

      {isViewOnly && (
        <div className="flex items-center gap-3 px-4 py-3 bg-blue-50 border border-blue-200 rounded-xl text-sm text-blue-700">
          <Eye className="w-4 h-4 shrink-0" />
          Mode consultation — les factures sont générées automatiquement par le système.
        </div>
      )}

      {/* Search */}
      <div className="bg-white rounded-xl p-4 shadow-sm border border-gray-200">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Rechercher une facture client..."
            className="w-full pl-11 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
          />
        </div>
      </div>

     {/* KPI Cards */}
<div className="grid grid-cols-1 md:grid-cols-4 gap-4">
  <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
    <div className="text-sm text-gray-600 mb-1">Total factures</div>
    <div className="text-2xl text-gray-900">
      {mappedDjangoInvoices.length}
    </div>
  </div>

  <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
    <div className="text-sm text-gray-600 mb-1">Montant total</div>
    <div className="text-2xl text-gray-900">
      {mappedDjangoInvoices
        .reduce((sum, inv) => sum + inv.amount, 0)
        .toLocaleString()} FCFA
    </div>
  </div>

  <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
    <div className="text-sm text-gray-600 mb-1">Payées</div>
    <div className="text-2xl text-green-600">
      {mappedDjangoInvoices.filter((invoice) => invoice.isPaid).length}
    </div>
  </div>

  <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
    <div className="text-sm text-gray-600 mb-1">Impayées</div>
    <div className="text-2xl text-red-600">
      {mappedDjangoInvoices.filter((invoice) => !invoice.isPaid).length}
    </div>
  </div>
</div>

      {/* Invoice Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs text-gray-500 uppercase tracking-wider">N° Facture</th>
                <th className="px-6 py-3 text-left text-xs text-gray-500 uppercase tracking-wider">Client</th>
                <th className="px-6 py-3 text-left text-xs text-gray-500 uppercase tracking-wider">Réf. BDC / BL</th>
                <th className="px-6 py-3 text-left text-xs text-gray-500 uppercase tracking-wider">Montant TTC</th>
                <th className="px-6 py-3 text-left text-xs text-gray-500 uppercase tracking-wider">Échéance</th>
                <th className="px-6 py-3 text-left text-xs text-gray-500 uppercase tracking-wider">Statut</th>
                <th className="px-6 py-3 text-left text-xs text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredInvoices.map((invoice) => {
                const dueDateStatus = getDueDateStatus(invoice.dueDate, invoice.isPaid);
                return (
                  <tr
                    key={invoice.id}
                    className="hover:bg-gray-50 cursor-pointer"
                    onClick={() => handleViewDetails(invoice)}
                  >
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{invoice.id}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{invoice.client}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-blue-600">
                      {invoice.bdcRef || "—"} / {invoice.blRef || "—"}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {invoice.amount.toLocaleString()} FCFA
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                      <div className="flex items-center gap-2">
                        <span className={`w-2 h-2 rounded-full ${dueDateStatus.color}`} />
                        <span className={`text-sm ${dueDateStatus.textColor}`}>
                          {new Date(invoice.dueDate).toLocaleDateString("fr-FR")}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className={`px-3 py-1 text-xs rounded-full ${statusConfig[invoice.status as keyof typeof statusConfig]?.color ?? "bg-gray-100 text-gray-700"}`}>
                          {statusConfig[invoice.status as keyof typeof statusConfig]?.label ?? invoice.status}
                        </span>
                        {invoice.autoGenerated && (
                          <span className="px-2 py-0.5 text-xs rounded-full bg-purple-100 text-purple-700 font-medium">
                           
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleViewDetails(invoice)}
                          className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition"
                          title="Voir détails"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                           {canEdit && invoice.status === "DRAFT" && (
  <button
    onClick={() => {
     const djangoInvoice = djangoInvoices.find(
  (inv: any) => inv.reference === invoice.id
);

if (!djangoInvoice) {
  console.error("Facture Django introuvable :", invoice.id);
  return;
}

setEditingInvoiceId(djangoInvoice.id);
      setFormData({
        client: invoice.client,
        bdcRef: invoice.bdcRef,
        blRef: invoice.blRef,
        deliveryId: "",
        issueDate: invoice.issueDate,
        dueDate: invoice.dueDate,
        tvaRate: invoice.tvaRate,
      });

      setFormItems(
  (invoice.items ?? []).map((item: any, index: number) => ({
    id: index + 1,
    designation: item.designation ?? "",
    quantity: Number(item.quantity ?? 0),
    unitPrice: Number(item.unitPrice ?? 0),
  }))
);
      setFormLocked(false);
      setShowModal(true);
    }}
    className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition"
    title="Modifier"
  >
    <Edit className="w-4 h-4" />
  </button>
)}

                       {canSend && invoice.status === "DRAFT" && (
                          <button
                            onClick={() => handleSendInvoice(invoice.id)}
                            className="p-2 text-green-600 hover:bg-green-50 rounded-lg transition"
                            title="Envoyer au client"
                          >
                            <Send className="w-4 h-4" />
                          </button>
                        )}
                        {canMarkPaid && !invoice.isPaid && (invoice.status === "sent" || invoice.status === "unpaid") && (
                          <button
                            onClick={() => setPayModal({ invoiceId: invoice.id, method: PAYMENT_METHODS[0] })}
                            className="p-2 text-green-600 hover:bg-green-50 rounded-lg transition"
                            title="Marquer comme payée"
                          >
                            <CheckCircle className="w-4 h-4" />
                          </button>
                        )}
                        {canDelete && (
                          <button
                            onClick={() => handleDelete(invoice.id)}
                            className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition"
                            title="Supprimer"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
              {filteredInvoices.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-6 py-10 text-center text-sm text-gray-500">
                    Aucune facture trouvée.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* New Invoice Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-gray-900/50 flex items-center justify-center z-50 p-4 overflow-y-auto">
          <div className="bg-white rounded-xl max-w-3xl w-full p-6 my-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl text-gray-900">Nouvelle facture client</h2>
              <button onClick={() => { setShowModal(false); resetForm(); }}>
                <X className="w-6 h-6 text-gray-400 hover:text-gray-600" />
              </button>
            </div>
            <form onSubmit={handleSubmit} className="space-y-5">
              {/* Client selector */}
              <div>
                <label className="block text-sm text-gray-700 mb-1">Sélectionner un client</label>
                <div className="flex gap-2">
                  <select
                    value={selectedClientRef}
                    onChange={(e) => handleClientSelect(e.target.value)}
                    className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none text-sm"
                  >
                    <option value="">— Choisir un client —</option>
                    {availableCustomerDeliveries.map((delivery: any) => (
                     <option key={delivery.id} value={delivery.id}>
                      {delivery.customer_detail?.raison_sociale ?? "-"} ({delivery.reference})
                   </option>
                 ))}
                  </select>
                  {formLocked && (
                    <button
                      type="button"
                      onClick={() => setFormLocked(false)}
                      className="flex items-center gap-1 px-3 py-2 border border-gray-300 text-gray-600 rounded-lg hover:bg-gray-50 text-sm"
                    >
                      Modifier
                    </button>
                  )}
                </div>
                {formLocked && (
                  <p className="mt-1 text-xs text-blue-600">Champs pré-remplis depuis le client sélectionné. Cliquez sur "Modifier" pour éditer manuellement.</p>
                )}
              </div>

              {/* Client + refs */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-gray-700 mb-1">Client *</label>
                  <input
                    type="text"
                    value={formData.client}
                    onChange={(e) => setFormData({ ...formData, client: e.target.value })}
                    className={`w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none ${formLocked ? "bg-gray-50 text-gray-500" : ""}`}
                    placeholder="Nom du client"
                    readOnly={formLocked}
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm text-gray-700 mb-1">Référence BDC / Devis</label>
                  <input
                    type="text"
                    value={formData.bdcRef}
                    onChange={(e) => setFormData({ ...formData, bdcRef: e.target.value })}
                    className={`w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none ${formLocked ? "bg-gray-50 text-gray-500" : ""}`}
                    placeholder="Ex: DEV-2024-050"
                    readOnly={formLocked}
                  />
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm text-gray-700 mb-1">Référence BL</label>
                  <input
                    type="text"
                    value={formData.blRef}
                    onChange={(e) => setFormData({ ...formData, blRef: e.target.value })}
                    className={`w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none ${blWarning ? "border-amber-400" : "border-gray-300"} ${formLocked ? "bg-gray-50 text-gray-500" : ""}`}
                    placeholder="Ex: BL-CLI-2024-025"
                    readOnly={formLocked}
                  />
                  {blWarning && (
                    <p className="mt-1 text-xs text-amber-700 flex items-center gap-1">
                      <span>⚠</span> Une facture a déjà été générée automatiquement pour ce BL.
                    </p>
                  )}
                </div>
                <div>
                  <label className="block text-sm text-gray-700 mb-1">Date de facture *</label>
                  <input
                    type="date"
                    value={formData.issueDate}
                    onChange={(e) => setFormData({ ...formData, issueDate: e.target.value })}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm text-gray-700 mb-1">Date d'échéance *</label>
                  <input
                    type="date"
                    value={formData.dueDate}
                    onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                    required
                  />
                </div>
              </div>
              <div className="w-32">
                <label className="block text-sm text-gray-700 mb-1">TVA %</label>
                <input
                  type="number"
                  min="0"
                  max="100"
                  step="0.1"
                  value={formData.tvaRate}
                  onChange={(e) => setFormData({ ...formData, tvaRate: parseFloat(e.target.value) || 0 })}
                  className={`w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none ${formLocked ? "bg-gray-50 text-gray-500" : ""}`}
                  readOnly={formLocked}
                />
              </div>

              {/* Items */}
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-sm text-gray-700">Lignes de facture *</label>
                  {!formLocked && (
                    <button
                      type="button"
                      onClick={handleAddFormItem}
                      className="text-sm text-blue-600 hover:text-blue-700 flex items-center gap-1"
                    >
                      <Plus className="w-4 h-4" />
                      Ajouter une ligne
                    </button>
                  )}
                </div>
                <div className="border border-gray-300 rounded-lg p-4 space-y-3 max-h-64 overflow-y-auto">
                  <div className="grid grid-cols-12 gap-2 pb-2 border-b border-gray-200">
                    <div className="col-span-5 text-xs text-gray-500 uppercase">Désignation</div>
                    <div className="col-span-2 text-xs text-gray-500 uppercase">Quantité</div>
                    <div className="col-span-3 text-xs text-gray-500 uppercase">Prix HT</div>
                    <div className="col-span-2 text-xs text-gray-500 uppercase">Total</div>
                  </div>
                  {formItems.map((item) => (
                    <div key={item.id} className="grid grid-cols-12 gap-2 items-center">
                      <input
                        type="text"
                        placeholder="Désignation"
                        value={item.designation}
                        onChange={(e) => handleFormItemChange(item.id, "designation", e.target.value)}
                        className={`col-span-5 px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-1 focus:ring-blue-500 ${formLocked ? "bg-gray-50 text-gray-500" : ""}`}
                        readOnly={formLocked}
                        required
                      />
                      <input
                        type="number"
                        placeholder="Qté"
                        min="1"
                        value={item.quantity}
                        onChange={(e) => handleFormItemChange(item.id, "quantity", parseInt(e.target.value) || 1)}
                        className={`col-span-2 px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-1 focus:ring-blue-500 ${formLocked ? "bg-gray-50 text-gray-500" : ""}`}
                        readOnly={formLocked}
                        required
                      />
                      <input
                        type="number"
                        placeholder="Prix unitaire"
                        min="0"
                        step="0.01"
                        value={item.unitPrice}
                        onChange={(e) => handleFormItemChange(item.id, "unitPrice", parseFloat(e.target.value) || 0)}
                        className={`col-span-3 px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-1 focus:ring-blue-500 ${formLocked ? "bg-gray-50 text-gray-500" : ""}`}
                        readOnly={formLocked}
                        required
                      />
                      <div className="col-span-2 flex items-center justify-between">
                        <span className="text-sm text-gray-900">{(item.quantity * item.unitPrice).toLocaleString()}</span>
                        {!formLocked && formItems.length > 1 && (
                          <button type="button" onClick={() => handleRemoveFormItem(item.id)} className="text-red-500 hover:text-red-700 ml-1">
                            <X className="w-4 h-4" />
                          </button>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Totals */}
              <div className="bg-gray-50 rounded-lg p-4 space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Sous-total HT :</span>
                  <span className="text-gray-900">{calcSubtotal().toLocaleString()} FCFA</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">TVA ({formData.tvaRate}%) :</span>
                  <span className="text-gray-900">{calcTVA().toLocaleString(undefined, { maximumFractionDigits: 0 })} FCFA</span>
                </div>
                <div className="flex justify-between border-t border-gray-300 pt-2">
                  <span className="text-gray-900 font-medium">Total TTC :</span>
                  <span className="text-xl text-gray-900 font-semibold">{calcTotal().toLocaleString(undefined, { maximumFractionDigits: 0 })} FCFA</span>
                </div>
              </div>

              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => { setShowModal(false); resetForm(); }}
                  className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition"
                >
                  Annuler
                </button>
                <button
                  type="submit"
                  className="flex-1 px-4 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-lg hover:from-blue-700 hover:to-indigo-700 transition"
                >
                  Créer la facture
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Detail Modal */}
      {showDetailModal && selectedInvoice && (
        <div className="fixed inset-0 bg-gray-900/50 flex items-center justify-center z-50 p-4 overflow-y-auto">
          <div className="bg-white rounded-xl max-w-2xl w-full p-6 my-8">
            <div className="flex items-center justify-between mb-5">
              <div>
                <h2 className="text-xl text-gray-900">{selectedInvoice.id}</h2>
                {selectedInvoice.autoGenerated && (
                  <span className="inline-block mt-1 px-2 py-0.5 text-xs rounded-full bg-purple-100 text-purple-700 font-medium">
                    
                  </span>
                )}
              </div>
              <button onClick={() => setShowDetailModal(false)}>
                <X className="w-6 h-6 text-gray-400 hover:text-gray-600" />
              </button>
            </div>

            {/* Header grid */}
            <div className="grid grid-cols-2 gap-4 mb-5">
              <div>
                <span className="text-xs text-gray-500 uppercase">Client</span>
                <p className="text-gray-900 mt-0.5">{selectedInvoice.client}</p>
              </div>
              <div>
                <span className="text-xs text-gray-500 uppercase">Statut</span>
                <div className="mt-1">
                  <span className={`px-3 py-1 text-xs rounded-full ${statusConfig[selectedInvoice.status as keyof typeof statusConfig]?.color ?? "bg-gray-100 text-gray-700"}`}>
                    {statusConfig[selectedInvoice.status as keyof typeof statusConfig]?.label ?? selectedInvoice.status}
                  </span>
                </div>
              </div>
              <div>
                <span className="text-xs text-gray-500 uppercase">Réf. BDC / Devis</span>
                <p className="text-blue-600 mt-0.5">{selectedInvoice.bdcRef || "—"}</p>
              </div>
              <div>
                <span className="text-xs text-gray-500 uppercase">Réf. BL</span>
                <p className="text-blue-600 mt-0.5">{selectedInvoice.blRef || "—"}</p>
              </div>
              <div>
                <span className="text-xs text-gray-500 uppercase">Date d'émission</span>
                <p className="text-gray-900 mt-0.5">{new Date(selectedInvoice.issueDate).toLocaleDateString("fr-FR")}</p>
              </div>
              <div>
                <span className="text-xs text-gray-500 uppercase">Échéance</span>
                <div className="flex items-center gap-2 mt-0.5">
                  <span className={`w-2 h-2 rounded-full ${getDueDateStatus(selectedInvoice.dueDate, selectedInvoice.isPaid).color}`} />
                  <p className={getDueDateStatus(selectedInvoice.dueDate, selectedInvoice.isPaid).textColor}>
                    {new Date(selectedInvoice.dueDate).toLocaleDateString("fr-FR")}
                  </p>
                </div>
              </div>
              {selectedInvoice.paidAt && (
                <div>
                  <span className="text-xs text-gray-500 uppercase">Date de paiement</span>
                  <p className="text-gray-900 mt-0.5">{new Date(selectedInvoice.paidAt).toLocaleDateString("fr-FR")}</p>
                </div>
              )}
              {selectedInvoice.paymentMethod && (
                <div>
                  <span className="text-xs text-gray-500 uppercase">Mode de paiement</span>
                  <p className="text-gray-900 mt-0.5">{selectedInvoice.paymentMethod}</p>
                </div>
              )}
            </div>

            {/* Items Table */}
            {selectedInvoice.items && selectedInvoice.items.length > 0 && (
              <div className="mb-5">
                <h3 className="text-sm font-medium text-gray-700 mb-2">Lignes de facture</h3>
                <div className="border border-gray-200 rounded-lg overflow-hidden">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-4 py-2 text-left text-xs text-gray-500 uppercase">Désignation</th>
                        <th className="px-4 py-2 text-right text-xs text-gray-500 uppercase">Qté</th>
                        <th className="px-4 py-2 text-right text-xs text-gray-500 uppercase">Prix HT</th>
                        <th className="px-4 py-2 text-right text-xs text-gray-500 uppercase">Total</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                      {selectedInvoice.items.map((item: any, idx: number) => (
                        <tr key={idx}>
                          <td className="px-4 py-2 text-gray-900">{item.designation}</td>
                          <td className="px-4 py-2 text-right text-gray-600">{item.quantity}</td>
                          <td className="px-4 py-2 text-right text-gray-600">{item.unitPrice.toLocaleString()} FCFA</td>
                          <td className="px-4 py-2 text-right text-gray-900">{item.total.toLocaleString()} FCFA</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Financial Summary */}
            {(() => {
              const subtotal = selectedInvoice.items?.reduce((s: number, i: any) => s + i.total, 0) ?? selectedInvoice.amount;
              const tvaRate = selectedInvoice.tvaRate ?? 18;
              const tvaAmount = subtotal * (tvaRate / 100);
              const totalTTC = subtotal + tvaAmount;
              return (
                <div className="bg-gray-50 rounded-lg p-4 space-y-2 mb-5">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">Sous-total HT :</span>
                    <span className="text-gray-900">{subtotal.toLocaleString()} FCFA</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">TVA ({tvaRate}%) :</span>
                    <span className="text-gray-900">{tvaAmount.toLocaleString(undefined, { maximumFractionDigits: 0 })} FCFA</span>
                  </div>
                  <div className="flex justify-between border-t border-gray-300 pt-2">
                    <span className="font-medium text-gray-900">Total TTC :</span>
                    <span className="text-xl font-semibold text-gray-900">{totalTTC.toLocaleString(undefined, { maximumFractionDigits: 0 })} FCFA</span>
                  </div>
                </div>
              );
            })()}

            {/* Action Buttons */}
            <div className="flex gap-3 flex-wrap">
             {canSend && selectedInvoice.status === "DRAFT" && (
  <button
    onClick={() => handleSendInvoice(selectedInvoice.id)}
    className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition text-sm"
  >
    <Send className="w-4 h-4" />
    Envoyer au client
  </button>
)}

                 {canValidate && selectedInvoice.status === "SENT" && (
                 <button
                  onClick={() => handleValidateInvoice(selectedInvoice.id)}
                   className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition text-sm"
                       >
                   <CheckCircle className="w-4 h-4" />
                    Valider par le client
                    </button>
               )}
               {canReject && selectedInvoice.status === "SENT" && (
  <button
    onClick={() => handleRejectInvoice(selectedInvoice.id)}
    className="flex items-center gap-2 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition text-sm"
  >
    <XCircle className="w-4 h-4" />
    Rejeter
  </button>
)}

              {canMarkPaid && !selectedInvoice.isPaid && (selectedInvoice.status === "sent" || selectedInvoice.status === "unpaid") && (
                <button
                  onClick={() => { setShowDetailModal(false); setPayModal({ invoiceId: selectedInvoice.id, method: PAYMENT_METHODS[0] }); }}
                  className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition text-sm"
                >
                  <CreditCard className="w-4 h-4" />
                  Marquer comme payée
                </button>
              )}
              {selectedInvoice.status === "paid" && (
                <div className="flex items-center gap-2 px-4 py-2 bg-green-50 text-green-700 rounded-lg text-sm">
                  <CheckCircle className="w-4 h-4" />
                  Facture payée{selectedInvoice.paymentMethod ? ` — ${selectedInvoice.paymentMethod}` : ""}
                </div>
              )}
              {canDelete && (
                <button
                  onClick={() => handleDelete(selectedInvoice.id)}
                  className="flex items-center gap-2 px-4 py-2 border border-red-300 text-red-600 rounded-lg hover:bg-red-50 transition text-sm"
                >
                  <Trash2 className="w-4 h-4" />
                  Supprimer
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Payment Modal */}
      {payModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-[60] p-4">
          <div className="bg-white rounded-xl max-w-md w-full p-6 shadow-xl">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Enregistrer le paiement</h3>
            <div className="mb-4">
              <label className="block text-sm text-gray-700 mb-1">Mode de paiement</label>
              <select
                value={payModal.method}
                onChange={e => setPayModal({ ...payModal, method: e.target.value })}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-green-500 outline-none"
              >
                {PAYMENT_METHODS.map(m => (
                  <option key={m} value={m}>{m}</option>
                ))}
              </select>
            </div>
            <div className="flex gap-3">
              <button
                onClick={() => setPayModal(null)}
                className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg text-sm hover:bg-gray-50"
              >
                Annuler
              </button>
              <button
                onClick={() => handleMarkPaid(payModal.invoiceId, payModal.method)}
                className="flex-1 px-4 py-2 bg-green-600 text-white rounded-lg text-sm hover:bg-green-700"
              >
                Confirmer le paiement
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
